language: 
 - python
python:
 - "2.7"

services: 
 - docker
before_install:
 - docker pull mitgcm/testreport-images:fc11-base-20170703
 - docker run --name fc11-testreport -t -d mitgcm/testreport-images:fc11-base-20170703  /bin/bash
 - docker exec -i fc11-testreport rpm -vv --rebuilddb
 - docker exec -i fc11-testreport df -h
 - docker exec -i fc11-testreport yum install python-pip
 
install: 
 - "pip install -r requirements.txt"
 - /bin/ls -altr
 - pwd

script: 
 - echo `pwd`
 - docker exec -i fc11-testreport df -h
 - python mytest_driver
