language: 
 - python
python:
 - "2.7"

services: 
 - docker
before_install:
 - docker pull mitgcm/testreport-images:centos-7.3.1611-20170809-v5
 - docker run  -v `pwd`:/MITgcm -h c7-n001 --name c7-n001 -d -t mitgcm/testreport-images:centos-7.3.1611-20170809-v5 /bin/bash
 - docker run  -v `pwd`:/MITgcm -h c7-n002 --name c7-n002 -d -t mitgcm/testreport-images:centos-7.3.1611-20170809-v5 /bin/bash
 - docker exec -t -i c7-n001 /usr/sbin/sshd
 - docker exec -t -i c7-n002 /usr/sbin/sshd
 - /bin/bash -s ./ci/travis/functions/set_container_hosts.sh
 
install: 
 - "pip install -r requirements.txt"
 - /bin/ls -altr
 - pwd

script: 
 - echo `pwd`
 - docker exec -i c7-n001 cat /etc/hosts
 - docker ps
 - python mytest_driver
