language: 
 - python
python:
 - "2.7"

services: 
 - docker
before_install:
 - docker pull mitgcm/testreport-images:fc11-base-20170703
 - docker run --name fc11-testreport -t -d mitgcm/testreport-images:fc11-base-20170703  /bin/bash
 - docker exec -i fc11-testreport rpm -vv --rebuilddb
 
install: 
 - "pip install -r requirements.txt"

script: 
 - python mytest_driver
