language: 
 - python
python:
 - "2.7"

services: 
 - docker
before_install:
 - docker pull mitgcm/testreport-images:fc11-base-20170703
 - docker run -t -d mitgcm/testreport-images:fc11-base-20170703  /bin/bash
 
install: 
 - "pip install -r requirements.txt"

script: 
 - python mytest_driver
